services:
  anchor:
    image: ghcr.io/zhfahim/anchor:latest
    container_name: anchor
    restart: unless-stopped
    ports:
      - "3029:3000"
    volumes:
      - anchor_data:/data

volumes:
  anchor_data: