services:
  spooty:
    image: raiper34/spooty:latest
    container_name: spooty
    restart: always
    ports:
      - "3013:3000"
    volumes:
      - "/home/rocket/Downloads:/spooty/backend/downloads"
