services:
  tugtainer:
    image: quenary/tugtainer:latest
    container_name: tugtainer
    ports:
      - "9412:80"
    volumes:
      - ./tugtainer_data:/tugtainer
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
