services:
  filebrowser:
    image: hurlenko/filebrowser:latest
    container_name: filebrowser # custom name
    user: "${UID}:${GID}"
    ports:
      - 3000:8080
    volumes:
      - "/home/rocket:/data" #*Navigation Home directory
      - ./config:/config
    environment:
      - FB_BASEURL=/filebrowser
      - FB_NOAUTH=true #!Added NoAuth so Family members can access without passwords
    restart: always

    #https://hub.docker.com/r/hurlenko/filebrowser